pr: none
trigger: none

jobs:
  - job: MacOS
    strategy:
      matrix:
        catalina-std:
          image: macOS-10.15
          platform: x86-64
          version: 10.13
          buildType: "standard"
          prefix: "synergy"
    pool:
      vmImage: $[ variables['image'] ]

    variables:
      QT_VERSION: '5.15.2'
      QT_PATH: '/usr/local/opt/qt'
      Qt5_DIR: '$(QT_PATH)/$(QT_VERSION)/clang_64'

    steps:
      - template: CI/checkout.yml
      - template: CI/MacOS/mac-build.yml